name: Lint

on:
  push:
    branches: ['main', 'release-prep', 'hotfix-*']
  pull_request:
    branches: ['main', 'release-prep', 'hotfix-*']

permissions:
  contents: read

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run format checking
        run: npm run format:check

      - name: Run all linters
        run: npm run lint
